[package]
name = "stack-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "stack_cli"
path = "src/lib.rs"

[[bin]]
name = "intel-npu-stack"
path = "src/main.rs"

[dependencies]
clap.workspace = true
serde_json.workspace = true
stack-core = { path = "../stack-core" }
stack-platform = { path = "../stack-platform" }
stack-runtime = { path = "../stack-runtime" }
stack-schema = { path = "../stack-schema" }

[dev-dependencies]
tempfile.workspace = true
